# Generated by Django 6.1.1 on 2026-10-07 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningresource',
            options={'ordering': ['-rating', 'title']},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='recommendationresource',
            options={'ordering': ['-relevance_score']},
        ),
        migrations.AlterModelOptions(
            name='recommendationskill',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['domain', 'name']},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AddField(
            model_name='learningresource',
            name='provider',
            field=models.CharField(default='Open Source / Web', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='match_score',
            field=models.FloatField(default=70.0, help_text='Market readiness match score (0-100%)'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='target_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recommendationskill',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Mastered')], default='todo', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationskill',
            name='timeline',
            field=models.CharField(default='Month 1', max_length=60),
        ),
        migrations.AddField(
            model_name='skill',
            name='domain',
            field=models.CharField(choices=[('web_dev', 'Full-Stack Web Development'), ('ai_ml', 'AI & Machine Learning'), ('data_science', 'Data Science & Analytics'), ('cloud_devops', 'Cloud & DevOps Engineering'), ('cybersecurity', 'Cybersecurity & Ethical Hacking'), ('ui_ux', 'UI/UX & Product Design'), ('product_management', 'Product & Agile Leadership'), ('soft_skills', 'Executive Communication & Soft Skills'), ('general', 'General Core Skills')], default='web_dev', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='fas fa-code', help_text='FontAwesome icon class', max_length=60),
        ),
        migrations.AddField(
            model_name='skill',
            name='market_demand',
            field=models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium')], default='High', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner (0-1 yrs)'), ('intermediate', 'Intermediate (1-3 yrs)'), ('advanced', 'Advanced (3+ yrs)'), ('career_switcher', 'Career Switcher')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_interest',
            field=models.CharField(choices=[('web_dev', 'Full-Stack Web Development'), ('ai_ml', 'AI & Machine Learning'), ('data_science', 'Data Science & Analytics'), ('cloud_devops', 'Cloud & DevOps Engineering'), ('cybersecurity', 'Cybersecurity & Ethical Hacking'), ('ui_ux', 'UI/UX & Product Design'), ('product_management', 'Product & Agile Leadership'), ('soft_skills', 'Executive Communication & Soft Skills')], default='web_dev', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_role',
            field=models.CharField(blank=True, default='Full-Stack Web Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_hours',
            field=models.IntegerField(default=10, help_text='Hours available per week for learning'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='confidence_score',
            field=models.IntegerField(default=50, help_text='1 to 100 confidence scale'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='duration_hours',
            field=models.FloatField(blank=True, default=12.0, null=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='rating',
            field=models.FloatField(blank=True, default=4.8, null=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='resource_type',
            field=models.CharField(choices=[('course', 'Course'), ('tutorial', 'Tutorial'), ('article', 'Article'), ('video', 'Video'), ('book', 'Book'), ('project', 'Hands-on Project')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='recommender.skill'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='groq_model_used',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('realtime_roadmap', 'Real-Time Career Roadmap'), ('skill_gap', 'Skill Gap Analysis'), ('learning_path', 'Learning Path'), ('career_advice', 'Career Advice')], default='realtime_roadmap', max_length=30),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommender.userprofile'),
        ),
        migrations.AlterField(
            model_name='recommendationresource',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='recommender.recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendationresource',
            name='relevance_score',
            field=models.FloatField(default=0.9),
        ),
        migrations.AlterField(
            model_name='recommendationresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_resources', to='recommender.learningresource'),
        ),
        migrations.AlterField(
            model_name='recommendationskill',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='recommender.recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendationskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_skills', to='recommender.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skills'), ('leadership', 'Leadership'), ('creative', 'Creative'), ('business', 'Business'), ('language', 'Language'), ('other', 'Other')], default='technical', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goals',
            field=models.TextField(blank=True, help_text='Career aspirations and goals'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma-separated or descriptive interests'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='recommender.skill'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='recommender.userprofile'),
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('web_dev', 'Full-Stack Web Development'), ('ai_ml', 'AI & Machine Learning'), ('data_science', 'Data Science & Analytics'), ('cloud_devops', 'Cloud & DevOps Engineering'), ('cybersecurity', 'Cybersecurity & Ethical Hacking'), ('ui_ux', 'UI/UX & Product Design'), ('product_management', 'Product & Agile Leadership'), ('soft_skills', 'Executive Communication & Soft Skills'), ('general', 'General Core Skills')], max_length=50)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('correct_option', models.CharField(choices=[('a', 'Option A'), ('b', 'Option B'), ('c', 'Option C'), ('d', 'Option D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='recommender.skill')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('assessed_level', models.CharField(default='Beginner', max_length=30)),
                ('feedback_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='recommender.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
